[package]
name = "ansible-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.40", features = ["clock"] }
crossterm = "0.28.1"
ratatui = "0.29.0"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "sync", "time", "process", "io-util"] }
walkdir = "2.5.0"
