use crate::task_preview::PlayPreview;

#[allow(dead_code)]
#[derive(Debug, Clone)]
pub enum Action {
    Tick,
    Quit,
    NextView,
    PrevView,
    MoveUp,
    MoveDown,
    SettingsIncrease,
    SettingsDecrease,
    ToggleLogSelectMode,
    MarkLogSelection,
    CopyLogSelection,
    CharInput(char),
    Backspace,
    LogMouseDown {
        row: u16,
        viewport_height: u16,
    },
    LogMouseDrag {
        row: u16,
        viewport_height: u16,
    },
    LogMouseUp,
    LogScrollUp,
    LogScrollDown,
    LogScrollPageUp,
    LogScrollPageDown,
    LogFollowLatest,
    ToggleCheckMode,
    ToggleDiffMode,
    SaveInventoryEditor,
    OpenRuntimePrompt,
    CloseRuntimePrompt,
    SelectRuntimeCandidate,
    BootstrapManagedRuntime,
    RuntimeBootstrapLog(String),
    RuntimeBootstrapFinished {
        success: bool,
        ansible_bin: Option<String>,
        message: String,
    },
    ProjectSyncLog(String),
    ProjectSyncFinished {
        success: bool,
        message: String,
    },
    VaultEditLoaded {
        success: bool,
        path: String,
        content: Option<String>,
        message: String,
    },
    RefreshProject,
    StartRun,
    StartTemplateRun,
    SaveTemplate,
    DeleteTemplate,
    RunStarted {
        run_id: u64,
        playbook: String,
        inventory: String,
        template_id: Option<String>,
    },
    RunLog {
        run_id: u64,
        line: String,
    },
    RunFinished {
        run_id: u64,
        success: bool,
        exit_code: Option<i32>,
    },
    PreviewTasks,
    TaskPreviewLog(String),
    TaskPreviewFinished {
        success: bool,
        plays: Vec<PlayPreview>,
        message: String,
    },
    Error(String),
}
